### ISSUE TITLE
[Request] api update request

### ISSUE THREAD

**Issue by JoshRyu** [JoshRyu/logistics#1]
@ZinnaChoi 

1. Read specific product
- there is a need for retrieving specific product by its id for product management page.
- endpoint would be /api/v1/product/{code} but "GET" method.

2. Create Product
- "img" attribute cannot be used at the moment. 

3. Swagger
- Currently, it is impossible to test other apis except "user login", due to bearer token authorization in headers.
- There's need for giving a space for adding headers in swagger sections or in other manner.
![image](https://github.com/JoshRyu/logistics/assets/37476263/22d9f2d4-6bff-4e8b-84db-33895d4f5654)
  - this is an authorization in the swagger, I put the user's auth token, which is a valid result from the login api, but it ain't work.

**Comment by ZinnaChoi** [comment]
hi, @JoshRyu !!

I Fix the 3. Swagger problem and now Bearer token works well. 
https://github.com/JoshRyu/logistics/pull/2

I understand the first issue and i will make the API after making all Swagger API works

however, i cannot understand the second issue
I think you need the "img" input for creating product

Can you provide more specific details about your requirements?
<img width="776" alt="image" src="https://github.com/JoshRyu/logistics/assets/142554606/e5dc46e2-9972-47f6-9fb6-f9b3f31d7c71">

**Comment by JoshRyu** [comment]
> hi, @JoshRyu !!
> 
> I Fix the 3. Swagger problem and now Bearer token works well. #2
> 
> I understand the first issue and i will make the API after making all Swagger API works
> 
> however, i cannot understand the second issue I think you need the "img" input for creating product
> 
> Can you provide more specific details about your requirements? <img alt="image" width="776" src="https://user-images.githubusercontent.com/142554606/281742078-e5dc46e2-9972-47f6-9fb6-f9b3f31d7c71.png">

Hey @ZinnaChoi thanks for the quick response!
yes, I need a image byte as an input for the api, but currently the image attribute is defined as string in JPA.
I'm requesting to test whether its possible to post image data itself rather than sending static path of the image.
