### ISSUE TITLE
[Note] Change the token authentication to use both an access token and a refresh token

### ISSUE THREAD

**Issue by ZinnaChoi** [JoshRyu/logistics#10]
Hi @JoshRyu 😺

We utilize JWT tokens for authentication; however, the expiration time is excessively long, posing a risk of token exposure by unauthorized parties. Shortening the expiration duration is not ideal as it may inconvenience users who need to log in frequently.

Therefore, **I propose a switch to token authentication using access and refresh tokens to address this issue.** While the priority of this matter may not be high, I'm making a note of it to ensure it isn't overlooked.

Thank you.

**Comment by JoshRyu** [comment]
Yes, when I initially design the login function, I was thinking to add refresh token for improving validation process.
Thanks for poining out, I won't close this issue until this propose is addressed 👍

**Comment by JoshRyu** [comment]
Refresh token is now added to main branch. closing the issue.

**Comment by JoshRyu** [comment]
Refresh token is now added to main branch. closing the issue.
