### ISSUE TITLE
[Fix Request] When executing the built jar, navigating to a page via a refresh or direct URL entry does not work

### ISSUE THREAD

**Issue by ZinnaChoi** [JoshRyu/logistics#33]
Hi @JoshRyu 

We are able to build and run the jar using the shell script, and navigation through button clicks within the application works fine. However, we encounter an issue where navigating to pages via a refresh or direct URL input fails.

![image](https://github.com/JoshRyu/logistics/assets/142554606/3e503264-ff43-479f-b76a-f4eeae9a1dda)

I think we need to address this issue promptly!

**Comment by JoshRyu** [comment]
Closing as issue closed
