### ISSUE TITLE
[Request] api update request

### ISSUE THREAD

**Issue by JoshRyu** [JoshRyu/logistics#7]
Hi @ZinnaChoi, I reckon we need following api endpoints for the next step.

1. Product 
- update /api/v1/product api to have pagination properties.

2. Category
- update /api/v1/category to receive ids as input rather than names? (ex: categoryName -> categoryCode)

3. Store
- CUD operations!

As always, thank you for your contribution :)

**Comment by ZinnaChoi** [comment]
We can close this issue~!
